const data = {
  products: [
    {
      _id: '1',
      name: 'Veg Burger',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 10,
    },
    {
      _id: '2',
      name: 'Chicken Broast',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 100,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 20,
    },
    {
      _id: '3',
      name: 'Al Faham',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 220,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
      countInStock: 0,
    },
    {
      _id: '4',
      name: 'Mutton Kebab',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 78,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
      countInStock: 50,
    },
    {
      _id: '5',
      name: 'Shawarma Roll',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 65,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
      countInStock: 10,
    },
    {
      _id: '6',
      name: 'Biryani',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 139,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
      countInStock: 10,
    },
  ],
};
export default data;